### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by mkoo**
Added new data template and added icons for external links

### CODE REVIEW

**Comment by tigerhawkvok** [comment]
Documentation branch is the one that ReadTheDocs updates from, it is distinct and ***should not*** be merged in with any other branch.

Just pushing the changes to the documentation branch should be enough to do the update. (I did see this Github email about a pull request :-P )

**Comment by mkoo** [comment]
Thanks!
MK

**Comment by tigerhawkvok** [comment]
@mkoo it did update, but the build failed:

https://readthedocs.org/projects/amphibian-disease-tracker/builds/7443967/

As I'm bashing my head on another issue at work I'll take a quick peek at this.

**Comment by tigerhawkvok** [comment]
Fixed build by pinning mkdocs version to 0.15.0 (we use the default provided by RTD, but the default braks with mkdocs 0.17.3)

**Pull request closed without merging**
